server:
  port: 8086
spring:
  application:
      name: zuul-router
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8082/eureka #ои
zuul:
  routes:
    entryapi:
      path: /entryapi/**
      serviceId: entry-service
  prefix: /v1