server:
    port: 9090

thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
          content-type: text/html
mvc:
    throw-exception-if-no-handler-found: true
